author:
  name: "Lucas Parreira"
  avatar: "/assets/images/avatar.png"
  bio: "Software Engineer (Data)"
  location: "Glasgow, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lucasnparreira"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/lucasnparreira"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/parreira_lucas"
feature_row_software:
  - image_path: /assets/images/time-system-teaser.jpg
    alt: "Time Tracking System"
    title: "Tracking System"
    excerpt: "A production-focused approach to employee time management."
    url: "/software/time-tracking-system/"
    btn_class: "btn--primary"
    btn_label: "Explore Architecture"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache